# Generated by Django 4.2.4 on 2023-08-18 18:48

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('img', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem')),
                ('tipo', models.CharField(choices=[('cerveja', 'Cerveja'), ('refrigerante', 'Refrigerante'), ('drink', 'Drink'), ('vinho', 'Vinho'), ('suco', 'Suco')], max_length=20, verbose_name='Tipo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
