# Generated by Django 4.2.4 on 2023-08-25 18:40

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('ingredientes', models.TextField(max_length=300, verbose_name='Ingredientes')),
                ('broto', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Preço Broto')),
                ('media', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Preço Media')),
                ('grande', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Preço Grande')),
                ('img', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem')),
                ('salgado', models.BooleanField(choices=[(1, 'Salgado'), (0, 'Doce')], verbose_name='Tipo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='bebida',
            name='tipo',
            field=models.CharField(choices=[('vinho', 'Vinho'), ('suco', 'Suco'), ('cerveja', 'Cerveja'), ('refrigerante', 'Refrigerante'), ('drink', 'Drink')], max_length=20, verbose_name='Tipo'),
        ),
    ]
