# Generated by Django 4.2.2 on 2023-09-28 23:29

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_combo_produto_delete_bebida_delete_pizza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='img',
            field=stdimage.models.StdImageField(default=1, force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
