# Generated by Django 4.2.2 on 2023-09-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_combo_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combo',
            old_name='pizza',
            new_name='produtos',
        ),
    ]
